import Link from 'next/link'
import './styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const links = [{
  label: 'To-Do List Page',
  route: '/'
}
]

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <head>
        <title>To-Do List App</title>
      </head>
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
